Ajout table paramètre et table rôle
CQEN-QDCE/pia-back pull request #1
Opened 2021-06-15 19:14 UTC by sebastiendesmarais-qc

2021-06-16 18:40 UTC, vorge requested changes

2021-06-16 18:40 UTC, vorge commented on db/migrate/20210510171950_create_parameters_site.rb
> +class CreateParametersSite < ActiveRecord::Migration[6.0]
Cette table sert à quoi?

2021-06-17 12:32 UTC, PierreJiji requested changes

2021-06-17 12:32 UTC, PierreJiji commented on db/migrate/20210510171950_create_parameters_site.rb
> +    create_table :parameters_sites do |t|
J'ajouterais le "id" de la table parameters_sites

2021-06-17 12:32 UTC, PierreJiji commented on db/migrate/20210615182326_create_role_utilisateur.rb
> +    create_table :role_utilisateurs do |t|
J'ajouterais le id de la table role_utilisateurs

2021-06-17 12:32 UTC, PierreJiji commented on db/migrate/20210615182326_create_role_utilisateur.rb
> +class CreateRoleUtilisateur < ActiveRecord::Migration[6.0]
Il serais mieux d'attacher cette table avec la tables pias parcequ'on a déja le vérificateur et aussi l'approbateur.
Il serais mieux aussi d'avoir deux tables à la place cette table ; Une table role_utilisateur (rédacteur, vérificateur et approbateur) qui est attaché avec la table pias et une autre table role_admin ( responsable CAI, pilote et administrateur)

2021-06-17 15:08 UTC, sebastiendesmarais-qc commented on db/migrate/20210510171950_create_parameters_site.rb
> +    create_table :parameters_sites do |t|
Par défaut, un champ ID est ajouté à la table

2021-06-17 15:08 UTC, sebastiendesmarais-qc commented on db/migrate/20210615182326_create_role_utilisateur.rb
> +    create_table :role_utilisateurs do |t|
Par défaut, un champ ID est ajouté à la table

2021-06-17 15:11 UTC, sebastiendesmarais-qc commented on db/migrate/20210615182326_create_role_utilisateur.rb
> +class CreateRoleUtilisateur < ActiveRecord::Migration[6.0]
Je crois que c'est discutable comme point. On pourra justement le faire à notre rencontre!

2021-06-17 18:38 UTC, PierreJiji commented on db/migrate/20210510171950_create_parameters_site.rb
> +    create_table :parameters_sites do |t|
Super ! À ce cas, Il serai mieux d'utiliser la meme structure que la communauté utilise
EX: create_table "measures", id: :serial, force: :cascade do |t|

2021-06-23 18:46 UTC, vorge commented on config/environments/development.rb
> +  config.hosts << "routeon9yiqpb-dess01-codeready.apps.exp.lab.pocquebec.org" #appsetting_json_parsed["url_backend_short"]
faudrait enlever ce fichier du commit

2021-06-28 12:55 UTC, vorge submitted a review, later dismissed

2021-06-28 19:54 UTC, vorge approved these changes

2021-06-28 20:08 UTC, PierreJiji approved these changes

2021-06-28 20:08 UTC, PierreJiji commented on .gitignore
> +/config/environnements/development.rb
Ce serait mieux de ne pas le mettre dans gitignore comme on a des conf à ajouter dans ce fichier spécialement pour le SMTP

2021-06-28 20:10 UTC, merged